apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
type: Opaque
data:
  auth: aGVucmlrOiRhcHIxJFovcUNmZXZrJGo2ay5FZFhEcktMOFVQVDVYZXJIUDE=
  # Use this guide https://kubernetes.github.io/ingress-nginx/examples/auth/basic/