
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-http01-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - talk-to-henrik'
  name: talk-to-me-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  ingressClassName: nginx
  rules:
  - host: talk-to-henrik.deepleap.se
    http:
      paths:
      - backend:
          service:
            name: talk-to-me-talk-to-me-aiui
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - talk-to-henrik.deepleap.se
    secretName: talk-to-me-tls-key-pair-prod
status:
  loadBalancer:
    ingress:
    - hostname: workaround.deepleap.se
