apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ include "talk-to-me-aiui.fullname" . }}
  labels:
    {{- include "talk-to-me-aiui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "talk-to-me-aiui.selectorLabels" . | nindent 4 }}
